apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicedemo-deploy
  labels:
    app: microservicedemo
  annotations:
spec:
  selector:
    matchLabels:
      app: microservicedemo
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: microservicedemo
    spec:
      containers:
        - name: microservicedemo
          image: jonasmaibohm/microservicedemo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
